[workspace]
resolver = "2"
members = [
    "seventy",
    "seventy-macros",

    "examples",
    "test-suite",
]

[workspace.dependencies]
seventy = { path = "seventy", features = ["full"] }
